MDScreen:
   MDBottomNavigation:
      panel_color: "#eeeaea"
      selected_color_background: "#97ecf8"
      text_color_active: 0, 0, 0, 1
   
      MDBottomNavigationItem:
         name: 'screen 1'
         text: 'Add'
         icon: 'plus'
      
         AddRecordScreen:

      MDBottomNavigationItem:
         name: 'screen 2'
         text: 'View List'
         icon: 'list-view'
         
         ViewRecordScreen